views:
  - title: Home
    sections:
      - type: grid
        cards:
          - type: heading
            heading_style: title
            heading: Kitchen
            icon: mdi:fridge
            badges:
              - type: entity
                show_state: false
                show_icon: true
                entity: binary_sensor.kitchen_counter_motion
                color: primary
          - type: tile
            entity: light.kitchen_spots
            features_position: bottom
            vertical: false
            show_entity_picture: false
            features:
              - type: light-brightness
          - type: tile
            features_position: bottom
            vertical: false
            entity: light.kitchen_counter_light
          - type: tile
            entity: light.kitchen_desk_light
            features_position: bottom
            vertical: false
          - type: tile
            entity: media_player.kitchen
            features_position: bottom
            vertical: false
      - type: grid
        cards:
          - type: heading
            heading: Bedroom
            heading_style: title
            icon: mdi:bed-king
            badges: []
          - type: tile
            features_position: bottom
            vertical: false
            entity: light.bedroom_bedside_light
          - type: tile
            entity: light.bedroom_spot_light
            features_position: bottom
            vertical: false
          - type: tile
            entity: binary_sensor.bedroom_window_opening
            features_position: bottom
            vertical: false
      - type: grid
        cards:
          - type: heading
            heading: Bathroom
            heading_style: title
            icon: mdi:shower-head
            badges:
              - type: entity
                show_state: true
                show_icon: true
                entity: sensor.bathroom_climate_temperature
                color: red
              - type: entity
                show_state: true
                show_icon: true
                entity: sensor.bathroom_climate_humidity
                color: indigo
              - type: entity
                show_state: false
                show_icon: true
                entity: binary_sensor.bathroom_motion_motion
                color: primary
          - type: tile
            features_position: bottom
            vertical: false
            entity: light.bathroom_mirror_light
          - type: tile
            entity: light.bathroom_ceiling_light
            features_position: bottom
            vertical: false
          - type: tile
            entity: binary_sensor.bathroom_window_opening
            features_position: bottom
            vertical: false
      - type: grid
        cards:
          - type: heading
            heading: Climate
            heading_style: title
            icon: mdi:thermometer
          - graph: line
            type: sensor
            entity: sensor.berlin_temperature
            detail: 1
            name: Temperature
          - type: tile
            features_position: bottom
            vertical: false
            entity: sensor.berlin_rain
          - type: tile
            entity: sun.sun
            features_position: bottom
            vertical: false
      - type: grid
        cards:
          - type: heading
            heading_style: title
            heading: Entrance
            icon: mdi:door-open
            badges:
              - type: entity
                show_state: false
                show_icon: true
                entity: binary_sensor.entrance_motion_motion
                color: primary
          - type: tile
            features_position: bottom
            vertical: false
            entity: lock.entrance_frontdoor_lock
          - type: tile
            entity: lock.aqara_smart_lock_u200
            features_position: bottom
            vertical: false
            name: Apartment Door
          - type: tile
            entity: light.kitchen_entrance_light
            features_position: bottom
            vertical: false
          - type: tile
            entity: binary_sensor.entrance_apartmentdoor_opening
            features_position: bottom
            vertical: false
            name: Door
      - type: grid
        cards:
          - type: heading
            heading_style: title
            heading: Updates
            icon: mdi:update
          - type: tile
            entity: update.home_assistant_supervisor_update
            features_position: bottom
            vertical: false
            name: Supervisior
            icon: mdi:home-assistant
          - type: tile
            entity: update.home_assistant_core_update
            features_position: bottom
            vertical: false
            icon: mdi:home-assistant
            name: Core
          - type: tile
            entity: update.home_assistant_operating_system_update
            features_position: bottom
            vertical: false
            name: OS
            icon: mdi:home-assistant
          - type: tile
            entity: automation.update_notifications
            features_position: bottom
            vertical: false
            name: Auto-update
            icon: mdi:rotate-right
            show_entity_picture: false
            tap_action:
              action: toggle
      - type: grid
        cards:
          - type: heading
            heading: Dining Area
            heading_style: title
            icon: mdi:silverware-fork-knife
          - type: tile
            entity: light.kitchen_table
            features_position: bottom
            vertical: false
          - type: tile
            entity: light.kitchen_fridge
            features_position: bottom
            vertical: false
    header:
      layout: start
      badges_position: top
      card:
        type: markdown
        content: '# Hello {{ user }}

          Add your text here, template variables are supported ✨'
        text_only: true
    badges:
      - type: entity
        show_name: true
        show_state: false
        show_icon: true
        entity: light.presence_simulation
        show_entity_picture: false
        icon: mdi:home-account
        tap_action:
          action: toggle
      - type: entity
        show_name: true
        show_state: false
        show_icon: true
        entity: switch.adaptive_lighting_kitchen
        name: Adaptive Lightning
        tap_action:
          action: toggle
        icon: mdi:weather-sunset
      - type: entity
        show_name: false
        show_state: true
        show_icon: true
        entity: person.dan
        show_entity_picture: true
    type: sections
    max_columns: 4
    dense_section_placement: false
    cards: []
